---
title: "Félidos de Costa Rica"
format: 
  html:
    theme: cosmo
    page-layout: custom
server: shiny
---

```{r}
#| label: inicio
#| context: setup
#| message: false

# Carga de paquetes
library(tidyverse)
library(DT)
library(sf)
```

```{r}
#| label: lectura-datos
#| context: data

# Lectura de archivo CSV
felidos <-
  st_read(
    dsn = "felidos.csv",
    options = c(
      "X_POSSIBLE_NAMES=decimalLongitude",
      "Y_POSSIBLE_NAMES=decimalLatitude"
    ),
    quiet = TRUE
  )
```

```{r}
#| panel: sidebar

# Vector ordenado de especies
lista_especies <- unique(felidos$species)
lista_especies <- sort(lista_especies)
lista_especies <- c("Todas", lista_especies)

# Selector de especies
selectInput(
  inputId = "especie",
  label = "Especie",
  choices = lista_especies,
  selected = "Todas"
)
```

```{r}
#| panel: fill

# Tabla interactiva
dataTableOutput("tabla")
```

```{r}
#| label: servidor
#| context: server

# Función reactiva para filtrar los registros de presencia de félidos
# de acuerdo con el valor de una lista de selección
filtrar_felidos <- reactive({
  # Valor inicial del objeto que va a retornarse
  felidos_filtrados <- felidos
  
  if (input$especie != "Todas") {
    felidos_filtrados <-
      felidos_filtrados |>
      filter(species == input$especie)
  }

  return(felidos_filtrados)
}) 
  
# Tabla con registros de presencia
output$tabla <- renderDataTable({
  felidos <- filtrar_felidos()
  
  felidos |>
    st_drop_geometry() |>
    select(species, stateProvince, locality, eventDate) |>
    datatable(
      colnames = c("Especie", "Provincia", "Localidad", "Fecha"),
      options = list(
        pageLength = 5,
        language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
      )
    )
})
```